#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

### Barvy ###
### Nord ###
bspc config normal_border_color		"#383c4a"
bspc config active_border_color 	"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"

bspc config border_width			2
bspc config window_gap				5
bspc config top_padding				25
bspc config focus_follows_pointer	true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle		 true
bspc config paddingless_monocle	 true

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^4'
bspc rule -a Lutris desktop='^5'
bspc rule -a Steam desktop='^5'
# DC Universe Online
bspc rule -a steam_app_24200 desktop='^5'
bspc rule -a WebApp-ForgeofEmpires9025 desktop='^5'
bspc rule -a vlc desktop='^6' follow=on
bspc rule -a Typora desktop='^7'

bspc rule -a Pavucontrol state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Gnome-calculator state=floating


bspc rule -a Oblogout state=floating
bspc config external_rules_command ~/.config/bspwm/scripts/external_rules.sh

# For Java applications
wmname LG3D

# Script for automatic starting programs after starting bspwm
$HOME/.config/autostart.sh


